name: "treebeard CI"
author: "treebeardtech"
description: "Automatically containerise and run notebooks"
inputs:
  api-key:
    description: "treebeard api key"
    required: false
  notebooks:
    description: "notebooks to run"
    required: false
    default: "**/*ipynb"
  docker-username:
    description: ""
    required: false
  docker-password:
    description: ""
    required: false
  docker-registry:
    description: ""
    required: false
  use-docker:
    description: "run treebeard inside repo2docker"
    required: false
    default: "true"
  debug:
    description: "Enable debug logging"
    required: false
    default: "false"
  path:
    description: "Path of the repo to run"
    required: false
    default: "."
    
runs:
  using: "node12"
  main: "dist/index.js"
