#!/bin/bash
set -euo pipefail
set -x

dir_name=$1

rm -rf "$dir_name"
git clone https://github.com/treebeardtech/hello_treebeard.git "$dir_name"

pushd "$dir_name"

pip install virtualenv
virtualenv venv

# shellcheck disable=SC1091
. venv/bin/activate

pip install -r requirements.txt

treebeard configure \
  --email robot@treebeard.io

treebeard status