#!/bin/bash
set -euo pipefail
set -x

# ensure we are in the script dir
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
pushd "$DIR"


rm -rf /tmp/local_install_test
mkdir /tmp/local_install_test
virtualenv /tmp/local_install_test/venv

# shellcheck disable=SC1091
. /tmp/local_install_test/venv/bin/activate

pip install -e ../treebeard-lib