#!/bin/bash
set -euo pipefail
set -x

# ensure we are in the script dir
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
pushd "$DIR"

dir_name="testrepo-$(date +%s)" # notebook_id will be the dir_name

./install_hello_repo "$dir_name"

pushd "$dir_name"
# shellcheck disable=SC1091
. venv/bin/activate
treebeard run --ignore venv --watch --local
