#!/usr/bin/env bash
set -xeuo pipefail

echo ::group::Running container_setup.ipynb
pip install git+https://github.com/treebeardtech/treebeard.git@local-docker#subdirectory=treebeard-lib

papermill \
  --stdout-file /dev/stdout \
  --stderr-file /dev/stderr \
  --kernel python3 \
  --no-progress-bar \
  treebeard/container_setup.ipynb \
  treebeard/container_setup.ipynb \

echo ::endgroup::
exec "$@"