#!/usr/bin/env bash
set -xeuo pipefail

echo Running treebeard/container_setup.ipynb
pip install -U git+https://github.com/treebeardtech/treebeard.git@local-docker#subdirectory=treebeard-lib > /dev/null

papermill \
  --stdout-file /dev/stdout \
  --stderr-file /dev/stderr \
  --kernel python3 \
  --no-progress-bar \
  treebeard/container_setup.ipynb \
  treebeard/container_setup.ipynb \

exec "$@"