#!/usr/bin/env bash
set -euo pipefail
set -x

# ensure we are in the script dir
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
pushd "$DIR"

api_key=$1
example_dir=$2

python -m pip install --upgrade pip	pipenv
./set_local_dependencies

pushd "$example_dir"
pip install ./treebeard-lib
treebeard configure --email robot@treebeard.io --api_key "$api_key"
treebeard run --watch --confirm_no_secrets