#!/usr/bin/env python
import sys
import shutil


def add_local_lib(directory: str):
    shutil.rmtree(f"{directory}/treebeard-lib", ignore_errors=True)
    shutil.copytree(
        f"{directory}/../../treebeard-lib", f"{directory}/treebeard-lib",
    )


def update_requirements_txt(directory: str):
    updated_reqs = []
    with open(f"{directory}/requirements.txt", "r") as f:
        for line in f.readlines():
            if line.startswith("treebeard"):
                updated_reqs.append("-e ./treebeard-lib\n")
            else:
                updated_reqs.append(line)

    print(updated_reqs)
    with open(f"{directory}/requirements.txt", "w") as f:
        f.writelines(updated_reqs)


def update_pipfile(directory: str):
    updated_reqs = []
    with open(f"{directory}/Pipfile", "r") as f:
        for line in f.readlines():
            if line.startswith("treebeard"):
                updated_reqs.append(
                    'treebeard = { editable = true, path = "./treebeard-lib" }\n'
                )
            else:
                updated_reqs.append(line)

    print(updated_reqs)
    with open(f"{directory}/Pipfile", "w") as f:
        f.writelines(updated_reqs)


if __name__ == "__main__":
    directory: str = sys.argv[1]
    add_local_lib(directory)

    if directory.endswith("reddit_tracker"):
        update_pipfile(directory)
    else:
        update_requirements_txt(directory)
