#!/usr/bin/env bash
set -euo pipefail
set -x

# ensure we are in the script dir
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
pushd "$DIR"

version=$(cat ../treebeard-lib/treebeard/version.txt)

update_requirements_txt() {
    sed s/"treebeard==$version/\-e \.\/treebeard-lib"/g "$1"/requirements.txt | tee "$1"/requirements.txt
}
update_pipfile() {
    sed "s/\"==$version\"/{editable = true,path = \".\"}/g" "$1"/Pipfile | tee "$1"/Pipfile
}

cp -R ../treebeard-lib google_cloud_storage
update_requirements_txt google_cloud_storage

cp -R ../treebeard-lib hello_treebeard
update_requirements_txt hello_treebeard

cp -R ../treebeard-lib national_grid
update_requirements_txt national_grid

cp -R ../treebeard-lib reddit_tracker
update_pipfile reddit_tracker