#!/bin/bash
set -euo pipefail
set -x

## Install, Configure, Run, Fetch like a new user
api_key=$1

# ensure we are in the script dir
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
pushd "$DIR"

# Use a new notebook ID each time to run without layer caching
dir_name="testrepo-new$(date +%s)"
cp -r ../examples/hello_treebeard ../examples/"$dir_name"

../examples/run_example_test "$api_key" "$dir_name"

# Check notebook has been stored
wget "https://api.treebeard.io/d8a0c5b6c9/${dir_name}/cli/main.ipynb?api_key=${api_key}&nbconvert=true"
